### ISSUE TITLE
Support new Crystallize image format

### ISSUE THREAD

**Issue by hakonkrogh** [CrystallizeAPI/react-image#1]
Since we now support a variable variants generation based on the image width, and also WebP, the package needs to be updated to reflect this.

Should we perhaps change the standard export to the ```<picture>``` el?

**Comment by hakonkrogh** [comment]
@didrikhegna @danisal

**Comment by meetdave3** [comment]
Fixed in - https://github.com/CrystallizeAPI/react-image/pull/2
Hence, closing
